apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: network-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: flask-app
        metrics_path: /metrics
        static_configs:
          - targets:
              - network-monitoring-app.network-monitoring.svc.cluster.local:80
